# Put main configuration in this file
# See http://seedstack.org/docs/seed/configuration for more information

logging:
  level: INFO

application:
  # Unique identifier of the application accross your organization
  id: hsweb
  # Make sure all your application base packages are listed below
  basePackages: [ com.hst.hsweb ]


security:
  # The security configuration realm uses the 'users' section below (replace it with a more useful realm later)
  # See http://seedstack.org/docs/seed/manual/security/#realms for more information
  realms: ConfigurationRealm
  users:
    # A default 'demo' user is defined with password 'demo'
    demo: demo

rest:
  path: /rest
  jspPath: /jsp
#  features:
#    - org.glassfish.jersey.server.mvc.freemarker.FreemarkerMvcFeature
#    - org.glassfish.jersey.server.mvc.jsp.JspMvcFeature
  jerseyProperties:
    jersey.config.server.tracing.type: ALL
    jersey.config.server.tracing.threshold: SUMMARY

web:
  server:
    port: 8081
    welcomeFiles:
      - test.html
      - index.html
      - hello.html

properties:
  user: Hervé

mongoDb:
  clients:
    hsweb:
      databases: hsweb
      uri: mongodb://localhost/hsweb

classes:
  com:
    hst:
      hsweb:
        mongoDbClient: hsweb
        mongoDbDatabase: hsweb
        com.mitchellbosecke.pebble.template.EvaluationContext@64518270: com.mitchellbosecke.pebble.template.PebbleTemplateImpl@3b7c58e7

